// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZayVp9NCWr-OrKDfS41DZgdidIa6TG9w',
    appId: '1:30464705100:web:1d1564a6f17b21f012aae9',
    messagingSenderId: '30464705100',
    projectId: 'vion-57e59',
    authDomain: 'vion-57e59.firebaseapp.com',
    storageBucket: 'vion-57e59.firebasestorage.app',
    measurementId: 'G-D4982KNWX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf0_AzKQLU-jeqiRjwO9yh_45DO6NqQ1w',
    appId: '1:30464705100:android:47e83efd5a81db1d12aae9',
    messagingSenderId: '30464705100',
    projectId: 'vion-57e59',
    storageBucket: 'vion-57e59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ6vVQIw2mN_sziHu6ujvHgQByxTOddcc',
    appId: '1:30464705100:ios:c0782a7fffd08bdc12aae9',
    messagingSenderId: '30464705100',
    projectId: 'vion-57e59',
    storageBucket: 'vion-57e59.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ6vVQIw2mN_sziHu6ujvHgQByxTOddcc',
    appId: '1:30464705100:ios:c0782a7fffd08bdc12aae9',
    messagingSenderId: '30464705100',
    projectId: 'vion-57e59',
    storageBucket: 'vion-57e59.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZayVp9NCWr-OrKDfS41DZgdidIa6TG9w',
    appId: '1:30464705100:web:15b2e68bb8d47d5512aae9',
    messagingSenderId: '30464705100',
    projectId: 'vion-57e59',
    authDomain: 'vion-57e59.firebaseapp.com',
    storageBucket: 'vion-57e59.firebasestorage.app',
    measurementId: 'G-1065YX9CXF',
  );

}